a=[]
b = input('возраст пользователя,')
v = input('возраст пользователя,')
g = input('имя пользователя,')
d = input('город пользователя,')
e = input('в каком классе пользователь учится.')
a.append(b)
a.append(v)
a.append(g)
a.append(d)
a.append(e)
print(a)